// SPDX-License-Identifier: BSD-3-Clause-Clear
pragma solidity ^0.8.24;

import {Script, console} from "forge-std/Script.sol";

/**
 * @title ComputeAddresses
 * @notice Step 1 of the two-phase FHEVM host deployment.
 *
 * Computes the deterministic CREATE addresses for all 5 UUPS proxies and
 * PauserSet, then writes them into FHEVMHostAddresses.sol so that the
 * implementation contracts can be compiled with the correct baked-in
 * addresses before the actual deployment runs.
 *
 * Usage (from forge-fhevm/):
 *
 *   DEPLOYER_PRIVATE_KEY=<key> forge script script/ComputeAddresses.s.sol \
 *       --rpc-url <rpc>
 *
 * After running this script, execute `forge build` and then run
 * DeployFHEVMHost.s.sol with the same deployer key and nonce.
 *
 * Deployment nonce layout (starting at N = deployer's nonce at script start):
 *
 *   N+0  EmptyUUPSProxyACL implementation
 *   N+1  ERC1967Proxy (ACL)              → aclAdd
 *   N+2  EmptyUUPSProxy implementation   (FHEVMExecutor slot)
 *   N+3  ERC1967Proxy (FHEVMExecutor)    → fhevmExecutorAdd
 *   N+4  EmptyUUPSProxy implementation   (KMSVerifier slot)
 *   N+5  ERC1967Proxy (KMSVerifier)      → kmsVerifierAdd
 *   N+6  EmptyUUPSProxy implementation   (InputVerifier slot)
 *   N+7  ERC1967Proxy (InputVerifier)    → inputVerifierAdd
 *   N+8  EmptyUUPSProxy implementation   (HCULimit slot)
 *   N+9  ERC1967Proxy (HCULimit)         → hcuLimitAdd
 *   N+10 PauserSet                       → pauserSetAdd
 */
contract ComputeAddresses is Script {
    // Path to FHEVMHostAddresses.sol relative to the foundry project root.
    string private constant ADDRESSES_FILE = "src/fhevm-host/addresses/FHEVMHostAddresses.sol";

    function run() external {
        address deployer = vm.addr(vm.envUint("DEPLOYER_PRIVATE_KEY"));
        uint64 nonce = vm.getNonce(deployer);

        address aclProxy = vm.computeCreateAddress(deployer, nonce + 1);
        address fhevmExecutorProxy = vm.computeCreateAddress(deployer, nonce + 3);
        address kmsVerifierProxy = vm.computeCreateAddress(deployer, nonce + 5);
        address inputVerifierProxy = vm.computeCreateAddress(deployer, nonce + 7);
        address hcuLimitProxy = vm.computeCreateAddress(deployer, nonce + 9);
        address pauserSetAddr = vm.computeCreateAddress(deployer, nonce + 10);

        console.log("Deployer:         ", deployer);
        console.log("Starting nonce:   ", nonce);
        console.log("aclAdd:           ", aclProxy);
        console.log("fhevmExecutorAdd: ", fhevmExecutorProxy);
        console.log("kmsVerifierAdd:   ", kmsVerifierProxy);
        console.log("inputVerifierAdd: ", inputVerifierProxy);
        console.log("hcuLimitAdd:      ", hcuLimitProxy);
        console.log("pauserSetAdd:     ", pauserSetAddr);

        string memory content = string.concat(
            "// SPDX-License-Identifier: BSD-3-Clause-Clear\n",
            "\n",
            "pragma solidity ^0.8.24;\n",
            "\n",
            "// Auto-generated by script/ComputeAddresses.s.sol - do not edit by hand.\n",
            "\n",
            "address constant aclAdd = address(",
            vm.toString(aclProxy),
            ");\n",
            "\n",
            "address constant fhevmExecutorAdd = address(",
            vm.toString(fhevmExecutorProxy),
            ");\n",
            "\n",
            "address constant kmsVerifierAdd = address(",
            vm.toString(kmsVerifierProxy),
            ");\n",
            "\n",
            "address constant inputVerifierAdd = address(",
            vm.toString(inputVerifierProxy),
            ");\n",
            "\n",
            "address constant hcuLimitAdd = address(",
            vm.toString(hcuLimitProxy),
            ");\n",
            "\n",
            "address constant pauserSetAdd = address(",
            vm.toString(pauserSetAddr),
            ");\n"
        );

        // forge-lint: disable-next-line(unsafe-cheatcode)
        vm.writeFile(ADDRESSES_FILE, content);
        console.log("\nFHEVMHostAddresses.sol written. Run `forge build` then DeployFHEVMHost.s.sol.");
    }
}
