#!/usr/bin/env bash

FHEVM_HOST_ADDRESSES_FILE="src/fhevm-host/addresses/FHEVMHostAddresses.sol"

load_dotenv_if_present() {
    local env_file="${1:-.env}"

    if [[ -f "$env_file" ]]; then
        set -a
        # shellcheck disable=SC1090
        source "$env_file"
        set +a
    fi
}

require_env_vars() {
    local var_name
    for var_name in "$@"; do
        if [[ -z "${!var_name:-}" ]]; then
            echo "Error: ${var_name} is required" >&2
            return 1
        fi
    done
}

require_one_of() {
    local description="$1"
    shift

    local var_name
    for var_name in "$@"; do
        if [[ -n "${!var_name:-}" ]]; then
            return 0
        fi
    done

    echo "Error: set ${description}" >&2
    return 1
}

is_truthy() {
    case "${1:-}" in
        1|true|TRUE|True|yes|YES|on|ON)
            return 0
            ;;
        *)
            return 1
            ;;
    esac
}

detect_rpc_client() {
    cast client --rpc-url "$RPC_URL" 2>/dev/null | tr '[:upper:]' '[:lower:]'
}

resolve_local_state_rpc_namespace() {
    if [[ -n "${LOCAL_STATE_RPC_NAMESPACE:-}" ]]; then
        case "$LOCAL_STATE_RPC_NAMESPACE" in
            anvil|hardhat)
                printf '%s\n' "$LOCAL_STATE_RPC_NAMESPACE"
                return 0
                ;;
            *)
                echo "Error: LOCAL_STATE_RPC_NAMESPACE must be 'anvil' or 'hardhat'" >&2
                return 1
                ;;
        esac
    fi

    local client
    client="$(detect_rpc_client)"

    if [[ "$client" == *anvil* ]]; then
        printf '%s\n' "anvil"
        return 0
    fi

    if [[ "$client" == *hardhat* ]]; then
        printf '%s\n' "hardhat"
        return 0
    fi

    echo "Error: could not detect a supported local RPC backend from \`cast client\` output: ${client:-<empty>}" >&2
    echo "Set LOCAL_STATE_RPC_NAMESPACE=anvil or LOCAL_STATE_RPC_NAMESPACE=hardhat explicitly." >&2
    return 1
}

resolve_forge_broadcast_pacing_flag() {
    if [[ -n "${FORGE_BROADCAST_PACING:-}" ]]; then
        case "$FORGE_BROADCAST_PACING" in
            slow)
                printf '%s\n' "--slow"
                return 0
                ;;
            fast)
                printf '%s\n' ""
                return 0
                ;;
            *)
                echo "Error: FORGE_BROADCAST_PACING must be 'slow' or 'fast'" >&2
                return 1
                ;;
        esac
    fi

    local client
    client="$(detect_rpc_client)"

    if [[ "$client" == *hardhat* ]]; then
        printf '%s\n' "--slow"
        return 0
    fi

    printf '%s\n' ""
}

resolve_signer_address() {
    local addr_var="$1"
    local pk_var="$2"

    if [[ -n "${!addr_var:-}" ]]; then
        printf '%s\n' "${!addr_var}"
        return 0
    fi

    cast wallet address --private-key "${!pk_var}" 2>/dev/null
}

pad_address() {
    local address_value="${1#0x}"
    printf '0x%064s\n' "$address_value" | tr ' ' '0'
}

write_fhevm_host_addresses() {
    local acl_address="$1"
    local executor_address="$2"
    local kms_verifier_address="$3"
    local input_verifier_address="$4"
    local hcu_limit_address="$5"
    local pauser_set_address="$6"

    cat >"$FHEVM_HOST_ADDRESSES_FILE" <<EOF
// SPDX-License-Identifier: BSD-3-Clause-Clear

pragma solidity ^0.8.24;

// Auto-generated by deploy scripts - do not edit by hand.

address constant aclAdd = address(${acl_address});

address constant fhevmExecutorAdd = address(${executor_address});

address constant kmsVerifierAdd = address(${kms_verifier_address});

address constant inputVerifierAdd = address(${input_verifier_address});

address constant hcuLimitAdd = address(${hcu_limit_address});

address constant pauserSetAdd = address(${pauser_set_address});
EOF
}

extract_address_constant_from_file() {
    local name="$1"
    local result
    result="$(sed -n "s/address constant ${name} = address(\\(0x[0-9A-Fa-f]*\\));/\\1/p" "$FHEVM_HOST_ADDRESSES_FILE")"
    if [[ -z "$result" ]]; then
        echo "Error: could not find address constant '${name}' in ${FHEVM_HOST_ADDRESSES_FILE}" >&2
        return 1
    fi
    printf '%s\n' "$result"
}
